apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::859679100707:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-GGN4MhEt9Fzh
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::859679100707:user/eshu
      username: eshu
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-11T16:26:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1115"
  uid: fdee7194-010e-4972-8a96-f6a47e7476f0
